\chapter{Mendefinisikan fungsi dan menangani kesalahan}
\section{Mendefinisikan fungsi}
\subsection{Fungsi Umum}
Mendefinisikan fungsi di Python menggunakan kata kunci \texttt{def}, dilanjutkan dengan nama fungsi dan argumen (jika ada). Perhatikan \lstlistingname~\ref{lst:fungsi}. Fungsi \texttt{perkalian} menerima 2 argumen yang dapat dioperasikan secara aritmatika, dalam hal ini perkalian. Kita tidak perlu mendefinisikan jenis variabel \texttt{a} dan \texttt{b} sebagai argumen di fungsi tersebut. Jika variabel yang diberikan dapat digunakan di dalam fungsi, maka program akan berjalan sesuai yang diharapkan.

\lstinputlisting[language=python, numbers=left, numberstyle=\small, caption=Mendefinisikan fungsi sederhana, showstringspaces=false, label=lst:fungsi]{script/fungsi.py}

\subsection{\texttt{Lambda}}
\texttt{Lambda} adalah teknik yang tersedia di Python untuk mendefinisikan fungsi yang sederhana. Perhatikan \figurename~\ref{fig:lambda}. Di gambar tersebut ditunjukkan fungsi \texttt{lambda} yang melakukan perkalian terhadap dua bilangan.

\begin{figure}
  \begin{center}
    \includegraphics[scale=2.0]{pics/lambda.png}
    \caption{Contoh sederhana fungsi \texttt{lambda}}
    \label{fig:lambda}
  \end{center}
\end{figure}

\section{Menangani kesalahan (\textit{exception})}
\label{sec:error}
Coba perhatikan kembali \lstlistingname~\ref{lst:ulang} di sub bab \ref{sec:kondisi}. Kita dapat mengidentifikasi terjadinya kesalahan selain mengidentifikasi penyebabnya. Karena pada beberapa kasus, penyebab kesalahan sulit diidentifikasi di awal. Perhatikan \lstlistingname~\ref{lst:error}. Di \lstlistingname~\ref{lst:error}, jalannya program akan dihentikan ketika nilai \texttt{b} yang berperan sebagai pembagi bernilai \texttt{0}. 

\lstinputlisting[language=python, numbers=left, numberstyle=\small, caption=Menghentikan perulangan ketika didapati operasi yang tidak valid, showstringspaces=false, label=lst:error]{script/tangkapError.py}
